### ISSUE TITLE
Add `-l` to the `NIGHTLY_OPTIONS` of the build

### ISSUE THREAD

**Issue by prakashsurya** [openzfs/openzfs-build#2]
The `README.md` states the following:

> NOTE: The -l option has been temporarily removed from from NIGHTLY_OPTIONS due to lint errors being reported and failing otherwise good builds. The failures are not yet understood, so they are being suppressed for the time being. This is not intended to be a long term fix; once the failures are investigated and/or fixed, this option will be re-enabled.

This **must** be fixed prior to the automated results actually being used for the illumos RTI process.

**Comment by prakashsurya** [comment]
I think the lint failures are due to this line in `build-os.sh`

```
log_must nightly_env_set_var "ONLY_LINT_DEFS"      "-I/opt/SUNWspro/sunstudio12.1/prod/include/lint"
```

and `/opt/SUNWspro` doesn't exist on OmniOS. This should probably be using `/opt`.

**Comment by prakashsurya** [comment]
@danmcd can you verify my above comment? I think I carried over the wrong path from our internal Delphix settings.

**Comment by danmcd** [comment]
Actually, it's /opt/sunstudio12.1/sunstudio12.1/prod/...
SPRO_ROOT should be /opt/sunstudio12.1 on OmniOS.

**Comment by prakashsurya** [comment]
Oh, ok.. that's good to know, I was setting `SPRO_ROOT` to `/opt` based on the wiki: http://wiki.illumos.org/display/illumos/How+To+Build+illumos

I'll update the build script to use `/opt/sunstudio12.1` and run it through testing.

**Comment by prakashsurya** [comment]
And just some additional verification, here's a build with lint enabled using the fix in https://github.com/openzfs/openzfs-build/commit/71edbd758b297a8f5e5699615cb448422d3c7227 which looks good to me: http://build.prakashsurya.com:8080/job/openzfs-build-nightly/29/console
